GET http://0.0.0.0/snippets

<> 2020-05-03T114441.200.json

###

POST http://0.0.0.0/login-register
Content-Type: application/json

{
  "user": "test",
  "password": "invalid-password"
}

<> 2020-05-03T114432.401.json

###

POST http://0.0.0.0/snippets
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "snippet": {
    "text": "hello-world-jwt"
  }
}

###

POST http://{{host}}/snippets
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "snippet": {
    "text": "hello-world-jwt"
  }
}

###

POST http://0.0.0.0/snippets
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "snippet": {
    "text": "hello-world-jwt"
  }
}

###

