# 注册
POST {{host}}/register
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ./
--WebAppBoundary--

###


# 上传文件
POST {{host}}/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="ktor_logo.svg";

< ../../resources/static/ktor_logo.svg
--WebAppBoundary--

###

# 登录
POST {{host}}/login
Content-Type: application/json

{
  "user_name": "",
  "password": "",
  "phone": "",
  "capture": "",
  "token": ""
}

###

# 片段
GET {{host}}/snippets
Accept: application/json


###

